const CART_ACTIONS = {
  PUT: 'cart/PUT',
  DELETE: 'cart/DELETE',
  SELECTIVE_DELETE: 'cart/SELECTIVE_DELETE',
  INITIALIZE: 'cart/INITIALIZE',
  GET: 'cart/GET',
};

const PRODUCT_LIST_ACTIONS = {
  INITIALIZE: 'productList/INITIALIZE',
};

const ORDER_ACTIONS = {
  ADD: 'order/ADD',
  DELETE: 'order/DELETE',
  INITIALIZE: 'order/INITIALIZE',
};

const AUTH_ACTIONS = {
  LOGIN: 'auth/LOGIN',
  LOGOUT: 'auth/LOGOUT',
};

const SNACKBAR_ACTIONS = {
  SHOW: 'snackbar/SHOW',
  HIDE: 'snackbar/HIDE',
};

export { CART_ACTIONS, PRODUCT_LIST_ACTIONS, ORDER_ACTIONS, AUTH_ACTIONS, SNACKBAR_ACTIONS };
