const PRODUCTS_ACTIONS = {
  UPDATE_PRODUCT_LIST_PENDING: 'UPDATE_PRODUCT_LIST_PENDING',
  UPDATE_PRODUCT_LIST_SUCCESS: 'UPDATE_PRODUCT_LIST_SUCCESS',
  UPDATE_PRODUCT_LIST_ERROR: 'UPDATE_PRODUCT_LIST_ERROR',
};

const CARTS_ACTIONS = {
  UPDATE_CART_LIST_PENDING: 'UPDATE_CART_LIST_PENDING',
  UPDATE_CART_LIST_SUCCESS: 'UPDATE_CART_LIST_SUCCESS',
  UPDATE_CART_LIST_ERROR: 'UPDATE_CART_LIST_ERROR',

  ADD_CART_LIST_PENDING: 'ADD_CART_LIST_PENDING',
  ADD_CART_LIST_SUCCESS: 'ADD_CART_LIST_SUCCESS',
  ADD_CART_LIST_ERROR: 'ADD_CART_LIST_ERROR',

  UPDATE_CART_ITEM_SUCCESS: 'UPDATE_CART_ITEM_SUCCESS',
  UPDATE_CART_ITEM_CHECKED: 'UPDATE_CART_ITEM_CHECKED',
  UPDATE_CART_ITEM_ALL_CHECKED: 'UPDATE_CART_ITEM_ALL_CHECKED',

  REMOVE_CART_ITEM_SUCCESS: 'REMOVE_CART_ITEM_SUCCESS',
  REMOVE_CART_ITEM_LIST_SUCCESS: 'REMOVE_CART_ITEM_LIST_SUCCESS',
};

const MEMBERS_ACTIONS = {
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',

  USER_INFO_REFRESH_SUCCESS: 'USER_INFO_REFRESH_SUCCESS',
  USER_INFO_REFRESH_ERROR: 'USER_INFO_REFRESH_ERROR',

  USER_PROFILE_EDIT_SUCCESS: 'USER_PROFILE_UPDATE',
  USER_PROFILE_EDIT_ERROR: 'USER_PROFILE_UPDATE_ERROR',

  USER_PASSWORD_CONFIRM_SUCCESS: 'USER_PASSWORD_CONFIRM_SUCCESS',
  USER_PASSWORD_CONFIRM_ERROR: 'USER_PASSWORD_CONFIRM_ERROR',

  USER_DROP_OUT_SUCCESS: 'USER_DROP_OUT_SUCCESS',
  USER_DROP_OUT_ERROR: 'USER_DROP_OUT_ERROR',

  USER_PASSWORD_EDIT_SUCCESS: 'USER_PASSWORD_EDIT_SUCCESS',
  USER_PASSWORD_EDIT_ERROR: 'USER_PASSWORD_EDIT_ERROR',

  USER_LOGOUT: 'USER_LOGOUT',
};

export { PRODUCTS_ACTIONS, CARTS_ACTIONS, MEMBERS_ACTIONS };
