const ACTION_TYPE = {
  CREATE_ORDER_PENDING: "order/CREATE_ORDER_PENDING",
  CREATE_ORDER_FULLFILLED: "order/CREATE_ORDER_FULLFILLED",
  CREATE_ORDER_REJECTED: "order/CREATE_ORDER_REJECTED",
};

export default ACTION_TYPE;
