const ACTION_TYPE = {
  CREATE_ORDER_PENDING: "order/CREATE_ORDER_PENDING",
  CREATE_ORDER_FULFILLED: "order/CREATE_ORDER_FULFILLED",
  CREATE_ORDER_REJECTED: "order/CREATE_ORDER_REJECTED",
};

export default ACTION_TYPE;
