export const ERROR_MESSAGE: { [key: number]: string } = {
  400: "400/(Bad Request) 이 응답은 잘못된 문법으로 인하여 서버가 요청을 이해할 수 없음",
  401: "401/(Unauthorized) 인증되지 않은 클라이언트",
  403: "403/(Forbidden) 클라이언트는 콘텐츠에 접근할 권리를 가지고 있지 않음",
  404: "404/(Not Found) 요청받은 리소스를 찾을 수 없음",
  405: "405/(Method Not Allowed) 요청한 메소드는 서버에서 알고 있지만, 제거되었고 사용할 수 없음",
  407: "407/(Proxy Authentication Required)프록시에 의해 완료된 인증이 필요",
  408: "408/(Request Timeout) 요청을 한지 시간이 오래된 연결에 일부 서버가 전송하며, 어떨 때에는 이전에 클라이언트로부터 어떠한 요청이 없었다고 하더라도 보내지기도 합니다. 이것은 서버가 사용되지 않는 연결을 끊고 싶어한다는 것을 의미",
  409: "409/(Conflict) 요청이 현재 서버의 상태와 충돌",
  410: "410/(Gone) 요청한 콘텐츠가 서버에서 영구적으로 삭제되었으며, 전달해 줄 수 있는 주소 역시 존재하지 않을 때 ",
  429: "429/(Too Many Requests) 지나치게 많은 요청",
  451: "451/(Unavailable For Legal Reasons) 사용자가 요청한 것은 정부에 의해 검열된 웹 페이지와 같은 불법적인 리소스",
  500: "500/(Internal Server Error) 서버가 처리 방법을 모르는 상황이 발생",
  503: "503/(Service Unavailable) 서버가 요청을 처리할 준비가 되지 않음",
  508: "508/(Loop Detected) 서버가 요청을 처리하는 동안 무한 루프를 감지",
  511: "511/(Network Authentication Required) 클라이언트가 네트워크 액세스를 얻기 위해 인증을 받아야 할 필요가 있음",
  0: "알 수 없는 오류가 발생했습니다.",
};
