const CURRENT_SERVER_LOCAL_STORAGE_KEY = 'API_BASE_URL';
const CART_LIST_LOCAL_STORAGE_KEY = 'CART_LIST';
const ORDERS_LOCAL_STORAGE_KEY = 'ORDERS';
const MEMBER_INFORMATION_LOCAL_STORAGE_KEY = 'MEMBER_INFORMATION';

export {
  CART_LIST_LOCAL_STORAGE_KEY,
  CURRENT_SERVER_LOCAL_STORAGE_KEY,
  ORDERS_LOCAL_STORAGE_KEY,
  MEMBER_INFORMATION_LOCAL_STORAGE_KEY,
};
