const CART_LIST_LOCAL_STORAGE_KEY = 'CART_LIST';
const CURRENT_SERVER_LOCAL_STORAGE_KEY = 'API_BASE_URL';
const ORDER_LIST_LOCAL_STORAGE_KEY = 'ORDER_LIST';
const MEMBER_STORAGE_KEY = 'MEMBER';

export {
  CART_LIST_LOCAL_STORAGE_KEY,
  CURRENT_SERVER_LOCAL_STORAGE_KEY,
  ORDER_LIST_LOCAL_STORAGE_KEY,
  MEMBER_STORAGE_KEY,
};
