const ACTION_TYPE = {
  SIGNUP_PENDING: "user/SIGNUP_PENDING",
  SIGNUP_FULLFILLED: "user/SIGNUP_FULLFILLED",
  SIGNUP_REJECTED: "user/SIGNUP_REJECTED",

  LOGIN_PENDING: "user/LOGIN_PENDING",
  LOGIN_FULLFILLED: "user/LOGIN_FULLFILLED",
  LOGIN_REJECTED: "user/LOGIN_REJECTED",

  SECESSION_PENDING: "user/SECESSION_PENDING",
  SECESSION_FULLFILLED: "user/SECESSION_FULLFILLED",
  SECESSION_REJECTED: "user/SECESSION_REJECTED",

  GET_USER_PENDING: "user/GET_USER_PENDING",
  GET_USER_FULLFILLED: "user/GET_USER_FULLFILLED",
  GET_USER_REJECTED: "user/GET_USER_REJECTED",

  UPDATE_USER_PASSWORD_PENDING: "user/UPDATE_USER_PASSWORD_PENDING",
  UPDATE_USER_PASSWORD_FULLFILLED: "user/UPDATE_USER_PASSWORD_FULLFILLED",
  UPDATE_USER_PASSWORD_REJECTED: "user/UPDATE_USER_PASSWORD_REJECTED",

  UPDATE_USER_GENERAL_INFO_PENDING: "user/UPDATE_USER_GENERAL_INFO_PENDING",
  UPDATE_USER_GENERAL_INFO_FULLFILLED: "user/UPDATE_USER_GENERAL_INFO_FULLFILLED",
  UPDATE_USER_GENERAL_INFO_REJECTED: "user/UPDATE_USER_GENERAL_INFO_REJECTED",
};

export default ACTION_TYPE;
