const ACTION_TYPE = {
  GET_ORDER_LIST_PENDING: "orderList/GET_ORDER_LIST_PENDING",
  GET_ORDER_LIST_FULLFILLED: "orderList/GET_ORDER_LIST_FULLFILLED",
  GET_ORDER_LIST_REJECTED: "orderList/GET_ORDER_LIST_REJECTED",
};

export default ACTION_TYPE;
