const ACTION_TYPE = {
  GET_CART_PENDING: "cart/GET_CART_PENDING",
  GET_CART_FULFILLED: "cart/GET_CART_FULFILLED",
  GET_CART_REJECTED: "cart/GET_CART_REJECTED",

  ADD_PRODUCT_TO_CART_PENDING: "cart/ADD_PRODUCT_TO_CART_PENDING",
  ADD_PRODUCT_TO_CART_FULFILLED: "cart/ADD_PRODUCT_TO_CART_FULFILLED",
  ADD_PRODUCT_TO_CART_REJECTED: "cart/ADD_PRODUCT_TO_CART_REJECTED",

  UPDATE_CART_ITEM_QUANTITY_PENDING: "cart/UPDATE_CART_ITEM_QUANTITY_PENDING",
  UPDATE_CART_ITEM_QUANTITY_FULFILLED:
    "cart/UPDATE_CART_ITEM_QUANTITY_FULFILLED",
  UPDATE_CART_ITEM_QUANTITY_REJECTED: "cart/UPDATE_CART_ITEM_QUANTITY_REJECTED",

  DELETE_CART_ITEMS_PENDING: "cart/DELETE_CART_ITEMS_PENDING",
  DELETE_CART_ITEMS_FULFILLED: "cart/DELETE_CART_ITEMS_FULFILLED",
  DELETE_CART_ITEMS_REJECTED: "cart/DELETE_CART_ITEMS_REJECTED",

  SELECT_CART_ITEM: "cart/SELECT_CART_ITEM",
  DESELECT_CART_ITEM: "cart/DESELECT_CART_ITEM",
  SELECT_ALL_CART_ITEMS: "cart/SELECT_ALL_CART_ITEMS",
  DESELECT_ALL_CART_ITEMS: "cart/DESELECT_ALL_CART_ITEMS",
};

export default ACTION_TYPE;
