const ACTION_TYPE = {
  UPDATE_PRODUCT_LIST_PENDING: "product/UPDATE_PRODUCT_LIST_PENDING",
  UPDATE_PRODUCT_LIST_FULLFILLED: "product/UPDATE_PRODUCT_LIST_FULLFILLED",
  UPDATE_PRODUCT_LIST_REJECTED: "product/UPDATE_PRODUCT_LIST_REJECTED",

  UPDATE_PRODUCT_DETAIL_PENDING: "product/UPDATE_PRODUCT_DETAIL_PENDING",
  UPDATE_PRODUCT_DETAIL_FULLFILLED: "product/UPDATE_PRODUCT_DETAIL_FULLFILLED",
  UPDATE_PRODUCT_DETAIL_REJECTED: "product/UPDATE_PRODUCT_DETAIL_REJECTED",
};

export default ACTION_TYPE;
