const ACTION_TYPE = {
  GET_PRODUCT_LIST_PENDING: "productList/GET_PRODUCT_LIST_PENDING",
  GET_PRODUCT_LIST_FULLFILLED: "productList/GET_PRODUCT_LIST_FULLFILLED",
  GET_PRODUCT_LIST_REJECTED: "productList/GET_PRODUCT_LIST_REJECTED",
};

export default ACTION_TYPE;
