const ACTION_TYPE = {
  GET_PRODUCT_DETAIL_PENDING: "productDetail/GET_PRODUCT_DETAIL_PENDING",
  GET_PRODUCT_DETAIL_FULLFILLED: "productDetail/GET_PRODUCT_DETAIL_FULLFILLED",
  GET_PRODUCT_DETAIL_REJECTED: "productDetail/GET_PRODUCT_DETAIL_REJECTED",
};

export default ACTION_TYPE;
