name: Frontend Deploy

on:
   push:
      branches:
         - step2

jobs:
   frontend:
      name: Frontend CICD
      runs-on: ubuntu-latest

      steps:
         - name: Checkout source code
           uses: actions/checkout@v2

         - name: Check Node Version 
           run: node -v

         - name: Cache node modules
           uses: actions/cache@v1
           with:
              path: node_modules
              key:
                 ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
              restore-keys: #일치하는 캐시 key가 없을 때 차선택으로 캐싱폴더를 찾는다.
                 ${{ runner.OS }}-build- ${{ runner.OS }}-

         - name: Install Dependencies
           run: npm install

         - name: Code Build
           run: npm run build

         - name: Configure AWS credentials #사용자 인증
           uses: aws-actions/configure-aws-credentials@v1
           with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_FRONT }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_FRONT }}
              aws-region: ap-northeast-2

         - name: Upload to S3
           env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_FRONT }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_FRONT }}
           run: aws s3 cp --recursive --region ap-northeast-2 ./build s3://eddy-web
