const USER_ACTION_TYPE = {
  SIGNUP_PENDING: "user/SIGNUP_PENDING",
  SIGNUP_FULFILLED: "user/SIGNUP_FULFILLED",
  SIGNUP_REJECTED: "user/SIGNUP_REJECTED",

  LOGIN_PENDING: "user/LOGIN_PENDING",
  LOGIN_FULFILLED: "user/LOGIN_FULFILLED",
  LOGIN_REJECTED: "user/LOGIN_REJECTED",

  LOGOUT: "user/LOGOUT",

  SECESSION_PENDING: "user/SECESSION_PENDING",
  SECESSION_FULFILLED: "user/SECESSION_FULFILLED",
  SECESSION_REJECTED: "user/SECESSION_REJECTED",

  GET_USER_PENDING: "user/GET_USER_PENDING",
  GET_USER_FULFILLED: "user/GET_USER_FULFILLED",
  GET_USER_REJECTED: "user/GET_USER_REJECTED",

  UPDATE_USER_PASSWORD_PENDING: "user/UPDATE_USER_PASSWORD_PENDING",
  UPDATE_USER_PASSWORD_FULFILLED: "user/UPDATE_USER_PASSWORD_FULFILLED",
  UPDATE_USER_PASSWORD_REJECTED: "user/UPDATE_USER_PASSWORD_REJECTED",

  UPDATE_USER_GENERAL_INFO_PENDING: "user/UPDATE_USER_GENERAL_INFO_PENDING",
  UPDATE_USER_GENERAL_INFO_FULFILLED: "user/UPDATE_USER_GENERAL_INFO_FULFILLED",
  UPDATE_USER_GENERAL_INFO_REJECTED: "user/UPDATE_USER_GENERAL_INFO_REJECTED",
};

export default USER_ACTION_TYPE;
